## library() calls go here
library(conflicted)
library(dotenv)
library(targets)
library(tarchetypes)
library(here)
library(tidyverse)
library(tsibble)
library(SPEI)
library(tsModel)
library(janitor)
library(lubridate)
library(mgcv)
library(dlnm)
library(bbmle)
library(glue)
library(patchwork)
library(broom)
library(gratia)
library(latex2exp)
library(parallel)
library(statmod)
library(rmarkdown)
library(colorspace)
library(Amelia)
library(readxl)
library(Hmisc)

conflict_prefer("select", "dplyr")
conflict_prefer("filter", "dplyr")
conflict_prefer("lag", "dplyr")
conflict_prefer("slice", "dplyr")
