---
title: "Model ANOVA tables with flowering in prev year as covariate"
author: "Eric R. Scott"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
## target knits Rmds in their own session, so load libraries here.
source(here::here("packages.R"))
```

```{r load-targets}
withr::with_dir(here(),{
  tar_load(c(s_cf_flwr, s_1ha_flwr, g_cf_flwr, g_1ha_flwr, f_cf_flwr, f_1ha_flwr))
  })
```

# Analysis

## Survival

### Continuous

```{r}
summary(s_cf_flwr)
```

```{r}
draw(s_cf_flwr)
```

### Fragments

```{r}
summary(s_1ha_flwr)
```

```{r}
draw(s_1ha_flwr)
```

## Growth

### Continuous

```{r}
summary(g_cf_flwr)
```

```{r}
draw(g_cf_flwr)
```

### Fragments

```{r}
summary(g_1ha_flwr)
```

## Flowering

### Continuous

```{r}
summary(f_cf_flwr)
```

```{r}
draw(f_cf_flwr)
```

### Fragments

```{r}
summary(f_1ha_flwr)
```

```{r}
draw(f_1ha_flwr)
```

## Reproducibility

<details>

<summary>

Reproducibility receipt

</summary>

```{r}
## datetime
Sys.time()

## repository
if(requireNamespace('git2r', quietly = TRUE)) {
  git2r::repository()
} else {
  c(
    system2("git", args = c("log", "--name-status", "-1"), stdout = TRUE),
    system2("git", args = c("remote", "-v"), stdout = TRUE)
  )
}

## session info
sessionInfo()
```

</details>
