
#' Convert demographic survey data into binary survival
#' 
#' This function might only make sense to use if you continue surveying for
#' plants long after you plan to count them as dead.  It is convenient if you
#' have many NA entries after a plant has died (or is assumed dead) and you want
#' to know which years it was alive and which it was dead.  You want to ignore
#' NAs that are not trailing and you want to ignore trailing NAs < n
#'
#' @param x any ordered numeric vector such as height, size, or number of shoots, that is collected every observation unless plants are not detected.
#' @param n number of successive, trailing missing survey points required to consider an organism dead.
#'
#' @return a binary vector with 1 = alive and 0 = assumed dead
#' @examples
#' #Assume plants dead with after not detected for 2 years
#' dead  <- c(1, 3, NA, NA, 1, 2, 1, NA, NA)
#' alive <- c(1, 3, NA, NA, 1, 2, 1, 3, NA)
#' as_living(dead)
#' as_living(alive)
as_living <- function(x, n = 2) {
  
  #if at least last 2 values are NA
  trail <- (length(x) - n + 1):length(x)
  #exclude negative indexes
  trail <- trail[trail >= 0]
  
  if(all(is.na(x))){
    alive <- rep(NA_integer_, length(x))
  } else if (all(is.na(x[trail]))) {
    #find the last non-NA value
    y <- cumsum(!is.na(x))
    last_real <- which.max(y == max(y))
    alive <- c(rep(1L, last_real), rep(0L, length(x) - last_real))
  } else {
    alive <- rep(1L, length(x))
  }
  return(alive)
}


#' Wrangle demography data
#'
#' Adds a binary columns for flowering and survival, calculates plant size, adds
#' columns for values in previous year, and sets appropriate columns to factors.
#' Removes leading and trailing NAs generated by converting from wide to long
#' format.
#'
#' @param data Heliconia demography dataset
#' @param n_years number of years missing before assumed dead (at last year
#'   recorded)
#'
wrangle_demog <- function(data, n_years = 3) {
  #Calculate binary survival column
  data_surv <-
    data %>% 
    group_by(ha_id_number) %>% 
    arrange(ha_id_number, year) %>% 
    mutate(surv = as_living(ht, n = n_years)) %>%  #1 if alive, 0 if dead (assumed dead after 2 trailing NAs)
    mutate(surv = if_else(!is.na(code_notes) & code_notes == "dead (2)", 0L, surv)) %>% 
    filter(surv == 1 | lag(surv) == 1) %>%  #remove entries after last year alive.
    filter(pmin(cumsum(!is.na(shts))) != 0) %>%  #remove leading NAs.
    ungroup()
  
  # add height and number shoots in the next year for each observation.
  # calculate size as shts * ht
  data_surv_size <-
    data_surv %>%
    group_by(ha_id_number) %>% 
    ungroup() %>% 
    mutate(
      size = shts * ht,
      log_size = log(size)
    )
  
  data_surv_size %>% 
    #add binary column for flowering
    mutate(infl = if_else(is.na(infl) & (!is.na(shts) | !is.na(ht)), 0L, infl)) %>% 
    mutate(flwr = if_else(infl > 0, 1L, 0L), .after = infl) %>% 
    #create factors
    mutate(across(
      c(ranch, bdffp_reserve_no, plot, habitat, ha_id_number),
      as.factor
    )) %>%
    mutate(year_fac = as.factor(year)) %>% 
    # arrange columns
    select(ranch, bdffp_reserve_no, plot, habitat, #site level
           ha_id_number, #plot level
           year,
           ht, shts, 
           size, log_size, 
           infl, flwr, surv,
           code_notes) %>% 
    
    # add lags
    group_by(ha_id_number) %>% 
    arrange(year) %>% 
    mutate(across(c(flwr, infl, ht, shts, size, log_size), lag,
                  .names = "{.col}_prev")) %>% 
    ungroup()
}

